name: Example Workflow

on:
  push:
  pull_request:
    types: [opened, closed]

jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: echo "An event has occurred"
